### ISSUE TITLE
Issue with the trim option

### ISSUE THREAD

**Issue by pboutin** [juliangruber/read-file-action#12]
Since the last release, we're experiencing issues with the new `trim` option. As I see, it should not be required but not defining it raise an exception.

![image](https://user-images.githubusercontent.com/4255460/119679951-c80c4900-be0e-11eb-87bb-18b59de96d05.png)

**Comment by MoshiCoCo** [comment]
I ran into the same problem, which caused the automatic build process of some of my repositories to fail.

**Comment by juliangruber** [comment]
Sorry about that, it's fixed now
