### ISSUE TITLE
Read specific key

### ISSUE THREAD

**Issue by navotera** [juliangruber/read-file-action#21]
I want to read specific key but it seems does not work with this code : 
- name: Echo package.json
        run: echo "${{ steps.package.outputs.content.version }}"
        
Maybe I miss something, any guidance is appreciated. 

Thank you

**Comment by juliangruber** [comment]
The content of `outputs.content` is a string and not yet a parsed object, so this should work:

```
run: echo "${{ JSON.parse(steps.package.outputs.content).version }}"
```

EDIT:

It's

```yaml
run: echo "${{ fromJson(steps.package.outputs.content).version }}"
```

**Comment by juliangruber** [comment]
Please reopen if it doesn't work like this :v:

**Comment by fiddlermikey** [comment]
Did this work for you?  @juliangruber  @navotera 
 I get the error :

> Unrecognized named-value: 'JSON'. Located at position 1 within expression: JSON.parse ...

**Comment by juliangruber** [comment]
You're right, it should be this:

```yaml
  run: echo "${{ fromJson(steps.package.outputs.content).version }}"
```
