### ISSUE TITLE
unexpected end of file error

### ISSUE THREAD

**Issue by pjirsa** [juliangruber/read-file-action#5]
Trying to read a simple JSON file. Contents are being output to action log. Then this message:
`/home/runner/work/_temp/3936fefc-fe31-4d66-bb34-75ead45f658f.sh: line 23: syntax error: unexpected end of file`

**Comment by juliangruber** [comment]
I don't see how the code could lead to this condition. Could you please share more about your action?

**Comment by pjirsa** [comment]
https://github.com/pjirsa/action-demo/blob/358380e2178e8db6eac8a03bf2f41d7a022c081d/.github/workflows/main.yml

Thanks for looking @juliangruber

**Comment by juliangruber** [comment]
I don't see that Workflow use this action 🤔

**Comment by pjirsa** [comment]
Sorry. i just updated comment to include correct commit

**Comment by juliangruber** [comment]
Thanks! This is because the file contains newlines. Try wrapping in quotation marks, like `echo "${...}"`

**Comment by juliangruber** [comment]
I'm closing this since I assume that fixes it. It is if anything more a GitHub Actions usage question than specifically about this action. Thanks for reporting :v:

**Comment by martijnvanschie** [comment]
Hi. I know this one is closed but I ran into a similar issue which was fixed by this thread :)

Perhaps its a good idea to put the quotes in the example on the actions page so ppl like me, who just copy and past the example for testing, know that this is a good practice.
https://github.com/marketplace/actions/read-file

**Comment by juliangruber** [comment]
Good idea!

https://github.com/juliangruber/read-file-action/releases/tag/v1.1.3
